---
- ContainerType: Unit
  Title: Requests and Responses
  Description: https://github.com/gSchool/spring-block/blob/master/standards/request-response/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/http-refresher.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/testing-endpoints.md
