---
- ContainerType: Unit
  Title: Requests and Responses
  Description: https://github.com/gSchool/spring-block/blob/master/standards/request-response/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/Ada-Developers-Academy/core-unit-1/blob/main/fundamentals/functions-overview.md
