---
- ContainerType: Unit
  Title: CNE Intro
  Description: https://github.com/gSchool/cloud-native-curriculum/blob/master/README.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-native-curriculum/blob/master/Course Content Overview.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-native-curriculum/blob/master/Course Format Video.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-native-curriculum/blob/master/Course Format Overview.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-native-curriculum/blob/master/Pace.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/intro/spring-boot.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/intro/getting-started.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/intro/submit-playground.md
- ContainerType: Unit
  Title: IDEs
  Description: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/README.md
  Contents:
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDE Preference.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDEA/Setting Up IDEA.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDEA/IDEA Maven.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDEA/IDEA Gradle.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDEA/IDEA Running Code.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/IDEA/IDEA Imports.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/Eclipse/Eclipse Maven.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/Eclipse/Eclipse Gradle.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/Eclipse/Eclipse Running Code.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/Eclipse/Eclipse Imports.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/IDEs/Checklist.md
- ContainerType: Unit
  Title: Requests and Responses
  Description: https://github.com/gSchool/spring-block/blob/master/standards/request-response/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/http-refresher.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/testing-endpoints.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/creating-endpoints.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/02-pi.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/accessing-querystring-data.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/03-calculate.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/accessing-path-variables.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/04-volume.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/testing-form-data.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/accessing-form-data.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/accessing-query-and-form-data.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/05-area.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/accessing-headers-and-cookies.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/debugging-tips.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/request-response/assessment.md
- ContainerType: Unit
  Title: JSON Endpoints
  Description: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/testing-json-responses.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/rendering-json-responses.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/converting-json-video.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/customizing-json.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/customizing-json-questions.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/handling-nested-json.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/01-flight.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/testing-json-request-data.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/accessing-json-request-data.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/02-ticket-total.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/json-and-immutable-classes.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/json-view.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/debugging.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/resources.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/json-endpoints/assessment.md
- ContainerType: Unit
  Title: Building CRUD APIs
  Description: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/install-mysql.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/mysql-questions.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/add-a-database-to-spring.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/adding-dependencies.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/refreshing-dependencies.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/intro-to-spring-config.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/jpa.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/ddl-auto.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/crud-endpoints.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/01-crud.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/testing-jpa-with-transactions.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/02-tests.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/handling-update-actions.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/03-handling-update-actions.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/jpa-custom-methods.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/04-jpa-methods.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/crud-apis/assessment.md
- ContainerType: Unit
  Title: Spring IoC and Config
  Description: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/ioc-overview-video.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/autowiring-beans.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/injection-types.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/misc-ioc-notes.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/01-setup.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/injecting-in-tests.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/02-test.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/configurationproperties.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/spring-developer-tools.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/config-lists.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/03-config.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/testing-config.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/04-config-test.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/ioc-and-config/assessment.md
- ContainerType: Unit
  Title: RestTemplates
  Description: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/readme.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/resttemplates-video.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/making-http-requests.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/01-omdb.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/setup-for-resttemplates.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/testing-resttemplates-video.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/testing-resttemplate-requests.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/02-testing.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-block/blob/master/standards/rest-templates/assessment.md
- ContainerType: Unit
  Title: Spring Security
  Description: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/README.md
  Contents:
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Add Spring Security.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Secure Endpoints by Role.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Testing.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Access Current User.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Authenticate with a Database.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Hash Passwords with BCrypt.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Authorization Assessment.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Spring Security/Resources.md
- ContainerType: Unit
  Title: Cloud Foundry
  Description: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/README.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Push Your First App.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Details of CF Push.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Cloud Foundry Video.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Cloud Foundry.md
  - Type: Exercise
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Cloud Foundry Questions.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Twelve Factor Applications.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Orgs and Spaces.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Push Java Apps.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Scale Apps.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Logs and Events.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Services.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Environment Variables.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Manifests.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Blue-Green Deploys Video.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Blue-Green Deploys.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Application Security Groups.md
  - Type: Lesson
    URL: https://github.com/gSchool/cloud-foundry-curriculum/blob/master/Standards.md
- ContainerType: Unit
  Title: "\U0001F6A7 REST"
  Description: https://github.com/gSchool/spring-curriculum/blob/master/REST/README.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/REST/Rest and HATEOAS.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/REST/HATEOAS.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/projects/spring-movies/05 - hateoas.md
  - Type: Exercise
    URL: https://github.com/gSchool/spring-curriculum/blob/master/REST/HATEOAS Assessment.md
- ContainerType: Unit
  Title: Testing
  Description: https://github.com/gSchool/spring-curriculum/blob/master/Testing/README.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/Testing Overview.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/Testing In Spring Video.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/Testing In Spring.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/AutoConfigureMockMvc.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/Mocking the Database.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Testing/TestRestTemplates.md
- ContainerType: Unit
  Title: Walkthroughs
  Description: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/README.md
  Contents:
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/Walkthrough - JPA Custom Methods.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/Walkthrough - HATEOAS.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/Walkthrough - Handling Update Actions.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/Walkthrough - RestTemplates.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Walkthroughs/Walkthrough - Testing RestTemplate Requests.md
  - Type: Lesson
    URL: https://github.com/gSchool/spring-curriculum/blob/master/Rest Templates/Integrating REST APIs Tutorial.md
